### ISSUE TITLE
Does num_massive_neutrinos matter?

### ISSUE THREAD

**Issue by msyriac** [msyriac/pyfisher#9]
We need to check if `num_massive_neutrinos` of 1 (CAMB default) vs. 3 (Planck analysis) makes any significant difference to derivatives and/or Fisher forecasts. Easiest thing to do first would be to make new derivs with `num_massive_neutrinos = 3` and see if you get the same constraints for a set of experiments that includes lensing Auto information from high-ell.

**Comment by msyriac** [comment]
Seems to not from @NamHoNguyen's analysis. Post a plot or table here so we can close this.

**Comment by nbatta** [comment]
@msyriac It matters for p(k)

**Comment by msyriac** [comment]
Could you post a plot with percent change?

**Comment by nbatta** [comment]
<img width="426" alt="Screen Shot 2020-02-06 at 12 57 38 PM" src="https://user-images.githubusercontent.com/702533/73964495-4a05f500-48e0-11ea-90df-dd701434d255.png">

**Comment by nbatta** [comment]
<img width="449" alt="Screen Shot 2020-02-06 at 12 59 46 PM" src="https://user-images.githubusercontent.com/702533/73964660-9f420680-48e0-11ea-98a3-f8d20d433200.png">

**Comment by nbatta** [comment]
<img width="460" alt="Screen Shot 2020-02-06 at 1 14 20 PM" src="https://user-images.githubusercontent.com/702533/73965732-aec24f00-48e2-11ea-9bcb-7275d5a2cb60.png">

**Comment by msyriac** [comment]
Thanks, these seem sub-percent. Might not have a noticeable effect on any mnu constraint as Nam found, but good to check again!

**Comment by nbatta** [comment]
It's important for things that integrate of p(k), like the mass function. I believe that what Nam found on CMB constraints.
